[build]
  command = "yarn export"
  publish = "out"

[build.environment]
  NODE_VERSION = "14.16.0"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "/wallet/*"
  to = "/wallet/[address].html"
  status = 200
  force = true
